name: openup
description: Video and voice calling app with strangers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.6.5
  freezed_annotation: ^0.14.3
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  firebase_core: ^1.10.1
  firebase_auth: ^3.3.0
  flutter_holo_date_picker: ^1.0.0-nullsafety.4
  http: ^0.13.3
  flutter_riverpod: ^1.0.0-dev.7
  location: ^4.3.0
  flutter_svg: ^0.22.0
  image_picker: ^0.8.4+2
  just_audio: ^0.9.13
  record: ^3.0.0
  intl: ^0.17.0
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.4
  path_provider: ^2.0.7
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.1
  freezed: ^0.14.5
  json_serializable: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/title.png
    - assets/images/connection_female.png
    - assets/images/connection_male.png
    - assets/images/heart.png
    - assets/images/friends_with_friends.png
    - assets/images/voice_call.png
    - assets/images/video_call.png
    - assets/images/preferences.png
    - assets/images/report.png
    - assets/images/profile.png
    - assets/images/connections_icon.svg
    - assets/images/rekindle_icon.svg
    - assets/images/support_icon.svg
    - assets/images/play_icon.svg
    - assets/images/pause_icon.svg
    - assets/images/double_hearts.png
    - assets/images/preferences_back.png
  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/myriad-pro-regular.otf
          weight: 400
        - asset: assets/fonts/myriad-pro-semibold.otf
          weight: 600
        - asset: assets/fonts/myriad-pro-semiboldit.otf
          weight: 600
          style: italic
        - asset: assets/fonts/myriad-pro-bold.otf
          weight: 700
        - asset: assets/fonts/myriad-pro-boldit.otf
          weight: 700
          style: italic
