name: openup
description: Video and voice calling app with strangers
publish_to: "none"
version: 1.1.3+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.6.5
  freezed_annotation: ^0.14.3
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  firebase_core: ^1.10.1
  firebase_auth: ^3.3.0
  http: ^0.13.3
  flutter_riverpod: ^1.0.0-dev.7
  flutter_svg: ^0.22.0
  image_picker: ^0.8.4+2
  just_audio: ^0.9.13
  record: ^3.0.0
  intl: ^0.17.0
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.4
  emoji_picker_flutter: ^1.0.8
  uuid: ^3.0.5
  rxdart: ^0.27.3
  connectycube_flutter_call_kit: ^2.0.2
  shared_preferences: ^2.0.11
  decorated_icon: ^1.2.1
  video_player: ^2.2.10
  syncfusion_flutter_sliders: ^19.4.43
  auto_size_text: ^3.0.0
  dartz: ^0.10.1
  top_snackbar_flutter: ^1.0.2
  get_it: ^7.2.0
  mixpanel_flutter: ^1.4.5
  image_crop: ^0.4.0
  lottie: ^1.2.2
  sentry_flutter: ^6.3.0
  image_cropper: ^1.5.0
  camerawesome: ^0.3.0+1
  path_provider: ^2.0.9
  path: ^1.8.0
  image: ^3.1.3
  url_launcher: ^6.0.20
  list_diff: ^2.0.1
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.1
  freezed: ^0.14.5
  json_serializable: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/title.png
    - assets/images/call.json
    - assets/images/video_call.json
    - assets/images/preferences.png
    - assets/images/report.png
    - assets/images/profile.png
    - assets/images/connections_icon.svg
    - assets/images/rekindle_icon.svg
    - assets/images/support_icon.svg
    - assets/images/play_icon.svg
    - assets/images/pause_icon.svg
    - assets/images/preferences_back.png
    - assets/images/friends.json
    - assets/images/heart.json
    - assets/images/friends_with_friends.gif
    - assets/images/double_dating.gif
    - assets/images/chevron_right.png
    - assets/images/close_circle.png
  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/myriad-pro-regular.otf
          weight: 400
        - asset: assets/fonts/myriad-pro-semibold.otf
          weight: 600
        - asset: assets/fonts/myriad-pro-semiboldit.otf
          weight: 600
          style: italic
        - asset: assets/fonts/myriad-pro-bold.otf
          weight: 700
        - asset: assets/fonts/myriad-pro-boldit.otf
          weight: 700
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon_ios.png"
