name: openup
description: Video and voice calling app with strangers
publish_to: "none"
version: 1.4.48+91

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.9.0
  collection: ^1.17.1
  dartz: ^0.10.1
  freezed_annotation: ^2.0.3
  http: ^1.1.0
  image: ^4.0.17
  intl: ^0.18.1
  json_annotation: ^4.7.0
  path: ^1.8.2
  rxdart: ^0.27.3
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  tuple: ^2.0.1
  uuid: ^3.0.5
  vector_math: ^2.1.2

  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^2.2.1
  decorated_icon: ^1.2.1
  device_info_plus: ^9.0.3
  fast_immutable_collections: ^9.1.5
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_remote_config: ^4.2.5
  flutter_animate: ^4.2.0
  flutter_apns:
    # Updated firebase deps in repo, but they have not pushed to pub as of 3/1/2023
    git:
      url: https://github.com/mwaylabs/flutter-apns/
      ref: master
      path: flutter_apns
  flutter_local_notifications: ^15.0.1
  flutter_riverpod: ^2.0.1
  flutter_svg: ^2.0.5
  go_router:
    # Persistent sibling navigators
    git:
      url: https://github.com/tolo/flutter_packages
      ref: fd5412f9bad9d511778b06e66a754454a409feea
      path: packages/go_router
  image_picker: ^1.0.2
  just_audio: ^0.9.34
  location: ^5.0.3
  lottie: ^2.1.0
  mixpanel_flutter: ^2.0.0
  path_provider: ^2.0.9
  permission_handler: ^10.1.0
  record: ^4.4.1
  sentry_flutter: ^7.9.0
  share_plus: ^7.1.0
  shared_preferences: ^2.1.2
  stack_trace: ^1.11.0
  url_launcher: ^6.1.6
  mic_stream: ^0.6.2
  photo_manager: ^2.5.2
  flutter_contacts: ^1.1.7
  audio_session: ^0.1.13
  infinite_scroll_pagination: ^4.0.0
  package_info_plus: ^4.1.0
  flutter_slidable: ^3.0.0
  google_maps_flutter: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.13.1

  freezed: ^2.1.1
  json_serializable: ^6.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/images/audio_indicator.svg
    - assets/images/call.json
    - assets/images/call.svg
    - assets/images/video_call.json
    - assets/images/play_icon.svg
    - assets/images/pause_icon.svg
    - assets/images/friends.json
    - assets/images/chevron_right.png
    - assets/images/chevron_right.svg
    - assets/images/close_circle.png
    - assets/images/location_off.svg
    - assets/images/location_search.png
    - assets/images/map_searching.json
    - assets/images/menu_background.png
    - assets/images/menu_button.png
    - assets/images/nav_icon_messages.svg
    - assets/images/nav_icon_people.svg
    - assets/images/onboard_discover.jpg
    - assets/images/onboard_chat.jpg
    - assets/images/onboard_countdown.jpg
    - assets/images/online.json
    - assets/images/people_background.png
    - assets/images/preferences_icon.png
    - assets/images/tutorial_photo_good.jpg
    - assets/images/signup_background.jpg
    - assets/images/signup_background.png
    - assets/images/signup_background/0.svg
    - assets/images/signup_background/1.svg
    - assets/images/signup_background/2.svg
    - assets/images/signup_background/3.svg
    - assets/images/signup_background/4.svg
    - assets/images/signup_background/5.svg
    - assets/images/signup_background/6.svg
    - assets/images/signup_friends_background.png
    - assets/images/signup_paper1.png
    - assets/images/signup_paper2.png
    - assets/images/subscribe_background.png
    - assets/images/earth.svg
    - assets/images/loading_icon.png
    - assets/images/videocam.svg
    - assets/images/welcome_background.png
    - assets/images/welcome_tile_background.png

  shaders:
    - assets/shaders/depth.frag

  fonts:
    - family: Neue Haas Unica
      fonts:
        - asset: assets/fonts/NeueHaasUnica-Thin.ttf
          weight: 100
        - asset: assets/fonts/NeueHaasUnica-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NeueHaasUnica-Light.ttf
          weight: 300
        - asset: assets/fonts/NeueHaasUnica-Regular.ttf
          weight: 400
        - asset: assets/fonts/NeueHaasUnica-Medium.ttf
          weight: 500
        - asset: assets/fonts/NeueHaasUnica-Bold.ttf
          weight: 600
        - asset: assets/fonts/NeueHaasUnica-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/NeueHaasUnica-Black.ttf
          weight: 800
        - asset: assets/fonts/NeueHaasUnica-ExtraBlack.ttf
          weight: 900
    - family: Covered By Your Grace
      fonts:
        - asset: assets/fonts/CoveredByYourGrace-Regular.ttf
          weight: 400
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Text-light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Text-Black.otf
          weight: 900


flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  min_sdk_android: 21
  adaptive_icon_background: "assets/images/app_icon_background.png"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  ios: true
  image_path_ios: "assets/images/app_icon_ios.png"
  remove_alpha_ios: true
