name: openup
description: Video and voice calling app with strangers
publish_to: "none"
version: 1.3.8+24

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.9.6
  freezed_annotation: ^2.0.3
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  firebase_core: ^1.10.1
  firebase_auth: ^3.3.0
  http: ^0.13.3
  flutter_riverpod: ^1.0.0-dev.7
  flutter_svg: ^1.1.0
  image_picker: ^0.8.5+3
  just_audio: ^0.9.21
  record: ^4.3.1
  intl: ^0.17.0
  firebase_messaging: ^13.0.1
  flutter_local_notifications: ^9.1.4
  emoji_picker_flutter: ^1.0.8
  uuid: ^3.0.5
  rxdart: ^0.27.3
  connectycube_flutter_call_kit: ^2.2.1
  shared_preferences: ^2.0.11
  decorated_icon: ^1.2.1
  video_player: ^2.2.10
  syncfusion_flutter_sliders: ^20.1.57
  auto_size_text: ^3.0.0
  dartz: ^0.10.1
  top_snackbar_flutter: ^2.1.1
  get_it: ^7.2.0
  mixpanel_flutter: ^2.0.0
  lottie: ^1.2.2
  sentry_flutter: ^6.3.0
  image_cropper: ^3.0.0
  camerawesome: ^0.3.0+1
  path_provider: ^2.0.9
  path: ^1.8.0
  image: ^3.1.3
  url_launcher: ^6.0.20
  list_diff: ^2.0.1
  tuple: ^2.0.0
  flutter_voip_push_notification:
    git: git@github.com:openup-app/flutter_voip_push_notification.git
  flutter_callkit_voximplant:
    git: git@github.com:openup-app/flutter_callkit.git
  location: ^4.4.0
  vector_math: ^2.1.2
  device_info_plus: ^4.1.0
  share_plus: ^4.0.10+1
  async: ^2.9.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.1
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.10.0
  json_annotation: ^4.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/call.json
    - assets/images/video_call.json
    - assets/images/play_icon.svg
    - assets/images/pause_icon.svg
    - assets/images/friends.json
    - assets/images/chevron_right.png
    - assets/images/close_circle.png
    - assets/images/onboard_discover.jpg
    - assets/images/onboard_chat.jpg
    - assets/images/onboard_countdown.jpg
    - assets/images/earth.svg
    - assets/images/loading_icon.png
    - assets/videos/welcome.mp4

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/myriad-pro-light.otf
          weight: 300
        - asset: assets/fonts/myriad-pro-regular.otf
          weight: 400
        - asset: assets/fonts/myriad-pro-semibold.otf
          weight: 600
        - asset: assets/fonts/myriad-pro-semiboldit.otf
          weight: 600
          style: italic
        - asset: assets/fonts/myriad-pro-bold.otf
          weight: 700
        - asset: assets/fonts/myriad-pro-boldit.otf
          weight: 700
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon_ios.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  remove_alpha_ios: true
