name: openup
description: Video and voice calling app with strangers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.6.5
  freezed_annotation: ^0.14.3
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.1
  freezed: ^0.14.5
  json_serializable: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/title.png
    - assets/images/connection_female.png
    - assets/images/connection_male.png
    - assets/images/heart.png
    - assets/images/friends_with_friends.png
    - assets/images/voice_call.png
    - assets/images/video_call.png
    - assets/images/preferences.png
  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/myriad-pro-regular.otf
          weight: 400
        - asset: assets/fonts/myriad-pro-semibold.otf
          weight: 600
        - asset: assets/fonts/myriad-pro-semiboldit.otf
          weight: 600
          style: italic
        - asset: assets/fonts/myriad-pro-bold.otf
          weight: 700
        - asset: assets/fonts/myriad-pro-boldit.otf
          weight: 700
          style: italic
